"""empty message

Revision ID: 3eba1c0f01d6
Revises: 7652fc803fbd
Create Date: 2023-08-07 03:27:50.375807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eba1c0f01d6'
down_revision = '7652fc803fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('title', sa.String(), nullable=True))
    op.add_column('products', sa.Column('wb_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'wb_id')
    op.drop_column('products', 'title')
    # ### end Alembic commands ###
