"""empty message

Revision ID: 438b892dda9a
Revises: cfce79de4f31
Create Date: 2023-09-13 17:50:20.146050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438b892dda9a'
down_revision = 'cfce79de4f31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rid', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_type', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('destination', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'destination')
    op.drop_column('orders', 'delivery_type')
    op.drop_column('orders', 'rid')
    # ### end Alembic commands ###
