"""empty message

Revision ID: 57334b893c10
Revises: ebff26955364
Create Date: 2023-10-18 14:12:33.175453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57334b893c10'
down_revision = 'ebff26955364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('warehouse', sa.String(), nullable=False),
    sa.Column('to_client', sa.Integer(), nullable=True),
    sa.Column('from_client', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
