"""empty message

Revision ID: 7652fc803fbd
Revises: 983862f17fb3
Create Date: 2023-08-07 03:27:16.466505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7652fc803fbd'
down_revision = '983862f17fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'title')
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'wb_id')
    op.drop_column('products', 'purchase_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('purchase_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('wb_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sale_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
