"""empty message

Revision ID: 983862f17fb3
Revises: 
Create Date: 2023-08-07 01:26:00.725625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983862f17fb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('wb_id', sa.String(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
