"""empty message

Revision ID: c6f4bba6f1af
Revises: 9067123346fc
Create Date: 2023-09-04 15:12:05.701837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f4bba6f1af'
down_revision = '9067123346fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
