"""empty message

Revision ID: c9898a27b570
Revises: 438b892dda9a
Create Date: 2023-09-13 17:51:21.770191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9898a27b570'
down_revision = '438b892dda9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('warehouse_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'warehouse_name')
    # ### end Alembic commands ###
